included:
  - Source

opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_acl
  - explicit_self
  - explicit_top_level_acl
  - file_name
  - file_types_order
  - function_default_parameter_at_end
  - implicit_return
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - strong_iboutlet
  - trailing_closure
  - unused_import
  - unused_private_declaration
  - vertical_whitespace_closing_braces
  - xct_specific_matcher