language: objective-c
osx_image: xcode10.2
addons:
  homebrew:
    packages:
    - swiftlint

stages:
  - lint
  - test
  # - name: docs
  #   if: branch = master

jobs:  
  include:
    - stage: lint
      name: "SwiftLint"
      script: 
        - swiftlint
    - stage: test
      name: "Unit Tests"
      xcode_project: OptionSelector.xcodeproj
      xcode_scheme: OptionSelector iOS
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone Xs
    # - stage: docs
    #   name: "Jazzy Documentation"
    
