language: objective-c
osx_image: xcode10.2
# addons:
#   homebrew:
#     packages:
#     - swiftlint

# xcode_project: OptionSelector.xcodeproj
# xcode_scheme: OptionSelector iOS
# xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone Xs

script:
  # - swiftlint
  - bundle exec jazzy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  email: bot@nickt.dev
  on:
    branch: master
